config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'todos#index'
  resources :todos, only: [:index, :new, :create, :update, :show]
  resources :sessions, only: [:new, :create]
  resources :users, only: [:show, :update]
  resources :user_avatars, only: [:show]

  match 'todos/:id/complete', to: "todos#destroy", via: [:get, :delete]
  match 'sessions', to: "sessions#destroy", via: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :todo
end

app/controllers/application_controller.rb
# coding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  attr_reader :current_user

  before_action :set_current_user
  after_action :unset_current_user

  private
  def set_current_user
    @current_user = User.where(id: session[:user_id]).first
    if @current_user
      return true
    else
      redirect_to new_session_path
    end
  end

  def unset_current_user
    @current_user = nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :set_current_user, only: [:new, :create]
  def new
    if session[:user_id]
      redirect_to todos_path
    else
      render :new
    end
  end

  def create
    @user = User.where("login = ? AND password = '#{auth_params[:password]}'", auth_params[:login]).first
    if @user
      @current_user = @user
      session[:user_id] = @user.id
      redirect_to root_url
      return true
    elsif User.find_by(login: auth_params[:login])
      flash.now[:alert] = "Incorrect password!"
    else
      flash.now[:alert] = "User not found!"
    end
    render :new
  end

  def destroy
    session[:user_id] = nil
    reset_session
    redirect_to root_url
  end

  protected
  def auth_params
    params.require(:user).permit(:login, :password)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :redirect_unauthenticated_users
  before_action :find_todo, only: [:show, :update, :destroy]

  def index
    @todos = Todo.where(user_id: current_user.id)
  end

  def show
    unless @todo
      render nothing: true, status: :not_found
    end
  end

  def new
  end

  def create
    @todo = Todo.create(body: params[:todo][:body], user_id: current_user.id)
    redirect_to todos_path
  end

  def update
    if @todo
      @todo.update_attributes(update_attrs)
      redirect_to todos_path
    else
      render nothing: true, status: :not_found
    end
  end

  def destroy
    if @todo
      @todo.destroy
      redirect_to todos_path
    else
      render nothing: true, status: :not_found
    end
  end

  protected
  def find_todo
    @todo = Todo.find_by(id: params[:id])
  end

  def update_attrs
    params.require(:todo).permit(:body, :user_id)
  end

  def redirect_unauthenticated_users
    unless session[:user_id]
      redirect_to controller: :sessions, action: :new
      return false
    end
  end
end

app/controllers/user_avatars_controller.rb
require 'open-uri'

class UserAvatarsController < ApplicationController
  def show
    user = User.find(params[:id])
    if user && user.avatar_url
      if stale?(user)
        send_data(open(user.avatar_url).read, disposition: 'inline', filename: File.basename(user.avatar_url))
      end
    else
      render nothing: true, status: :not_found
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user

  def show
    if @user && @current_user.id == @user.id
    elsif @user.nil?
      render nothing: true, status: :not_found
    else
      render nothing: true, status: :forbidden
    end
  end

  def update
    if @user
      @user.avatar_url = user_params[:avatar_url]
      @user.save
      redirect_to user_path(@user)
    else
      render nothing: true, status: :not_found
    end
  end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:avatar_url, :firstname, :lastname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title>Todo Security</title>
      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= favicon_link_tag asset_path('favicon.ico'), rel: 'icon', type: 'image/x-icon' %>
      <% if @current_user %>
          <%= image_tag(user_avatar_path(@current_user.id), size: "120x120") %>
          <%= form_for :session, method: :delete, url: { controller: :sessions, action: :destroy } do |f| %>
              <%= f.submit('logout') %>
          <% end %>
      <% end %>
  </head>

  <body>
    <% if flash.alert %>
        <div class="notice"><%= flash.alert %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>Todos:</h1>
<ul>
<% @todos.each do |todo| %>
    <ol>
        <%= form_for todo, method: :patch, url: { controller: :todos, action: :update, id: todo.id } do |f| %>
            <%= raw(todo.body) %>
            <%= f.text_field(:body) %>
            <%= f.submit('update') %>
        <% end %>
        <%= form_for todo, method: :delete, url: { controller: :todos, action: :destroy, id: todo.id } do |f| %>
            <%= f.submit('complete') %>
        <% end %>
    </ol>
<% end %>
</ul>

<!-- Link to create new todos -->
<%= form_for Todo.new,url: { action: :create } do |f| %>
    <%= f.text_field :body %>
    <%= f.submit '+' %>
<% end %>

app/views/todos/show.html.erb
<% if @todo %>
    <h1>Todo:</h1>
    <%= @todo.body %>
<% end %>

app/views/users/show.html.erb
<%= form_for :user, method: :patch, url: { controller: :users, action: :update, id: @current_user.id } do |f| %>
    <%= f.label(:first_name) %>
    <%= f.text_field(:firstname) %>
    <%= f.label(:last_name) %>
    <%= f.text_field(:lastname) %>
    <%= f.label(:avatar_url) %>
    <%= f.text_field(:avatar_url, value: @current_user.avatar_url) %>
    <%= f.submit(:submit) %>
<% end %>